title: Control a buzzer with Scratch 2
hero_image: images/banner.png
description: Sound a buzzer using Scratch 2
original_url:
theme: green
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: 
interests: 
technologies: "electronics, physical computing, scratch"
site_areas:
steps:
  - title: Sound a buzzer

